import type { EvaluationInput, GeneratedReport } from "@/lib/types";
import { sourceLabels, REPORT_FRAMEWORK_NOTE } from "@/lib/frameworks/literature-basis";

function list(items: string[]): string {
  if (!items.length) return "_None noted._\n";
  return items.map((i) => `- ${i}`).join("\n") + "\n";
}

export function reportToMarkdown(
  input: EvaluationInput,
  report: GeneratedReport,
): string {
  const ctx = input.context;
  const unit = input.unit;
  const p = report.scoreProfile;

  const lines: string[] = [];
  lines.push(`# CourseMap Evaluation Report`);
  lines.push("");
  lines.push(`**Coursebook:** ${unit.coursebookName} — ${unit.unitTitle}`);
  lines.push("");
  lines.push(
    `**Overall fit:** ${p.overallScore.toFixed(2)} / 5 — ${p.label}  `,
  );
  lines.push(
    `**Generated by:** ${report.generatedBy === "ai" ? "AI-supported (Anthropic)" : "Template-based fallback"}`,
  );
  lines.push("");

  lines.push(`## Evaluation overview`);
  lines.push(report.overview || "_No overview._");
  lines.push("");

  lines.push(`## Teaching context`);
  lines.push(`- Institution type: ${ctx.institutionType}`);
  lines.push(`- Learner level: ${ctx.learnerLevel}`);
  lines.push(`- Learner profile: ${ctx.learnerProfile || "—"}`);
  lines.push(`- Weekly hours: ${ctx.weeklyHours ?? "—"}`);
  lines.push(`- Course duration: ${ctx.courseDuration || "—"}`);
  lines.push(`- Course goal: ${ctx.courseGoal}`);
  lines.push(`- Assessment / exam alignment: ${ctx.examAlignment || "—"}`);
  lines.push(`- Learner needs: ${ctx.learnerNeeds || "—"}`);
  lines.push(`- Constraints: ${ctx.constraints || "—"}`);
  lines.push("");

  lines.push(`## Coursebook unit summary`);
  lines.push(`- Coursebook: ${unit.coursebookName}`);
  lines.push(`- Publisher: ${unit.publisher || "—"}`);
  lines.push(`- Level claimed by publisher: ${unit.claimedLevel || "—"}`);
  lines.push(`- Unit: ${unit.unitTitle}`);
  lines.push(`- Topic: ${unit.unitTopic || "—"}`);
  lines.push(`- Skills covered: ${unit.unitSkills.join(", ") || "—"}`);
  lines.push("");

  lines.push(`## Context-fit judgment`);
  lines.push(report.contextFitJudgment || "_Not available._");
  lines.push("");

  lines.push(`## Category scores`);
  lines.push("");
  lines.push(`| Category | Score | Literature basis |`);
  lines.push(`| --- | --- | --- |`);
  for (const c of p.categoryScores) {
    lines.push(
      `| ${c.categoryName} | ${c.score > 0 ? c.score.toFixed(2) : "—"} | ${sourceLabels(c.sourceAnchors).join(", ")} |`,
    );
  }
  lines.push("");

  lines.push(`## Key strengths`);
  lines.push(list(report.overallStrengths));
  lines.push(`## Main weaknesses`);
  lines.push(list(report.mainWeaknesses));

  lines.push(`## Evidence-based comments by category`);
  lines.push("");
  for (const c of report.categoryFeedback) {
    lines.push(`### ${c.category} — ${c.score > 0 ? c.score.toFixed(2) + "/5" : "not rated"}`);
    if (c.sourceAnchors.length)
      lines.push(`_Literature basis: ${sourceLabels(c.sourceAnchors).join(", ")}_`);
    lines.push("");
    lines.push(`**Interpretation:** ${c.interpretation}`);
    lines.push("");
    lines.push(`**Evidence:** ${c.evidence}`);
    lines.push("");
    lines.push(`**Adaptation need:** ${c.adaptationNeed}`);
    lines.push("");
  }

  lines.push(`## Adaptation plan`);
  lines.push("");
  lines.push(`### What to keep`);
  lines.push(list(report.adaptationPlan.keep));
  lines.push(`### What to cut`);
  lines.push(list(report.adaptationPlan.cut));
  lines.push(`### What to simplify`);
  lines.push(list(report.adaptationPlan.simplify));
  lines.push(`### What to supplement`);
  lines.push(list(report.adaptationPlan.supplement));
  lines.push(`### What to reorder`);
  lines.push(list(report.adaptationPlan.reorder));

  lines.push(`## Ready-made supplementary tasks`);
  lines.push("");
  report.supplementaryTasks.forEach((t, i) => {
    lines.push(`### Task ${i + 1}: ${t.title}`);
    lines.push(`- **Aim:** ${t.aim}`);
    lines.push(`- **Level:** ${t.level}`);
    lines.push(`- **Time:** ${t.time}`);
    if (t.interaction) lines.push(`- **Interaction:** ${t.interaction}`);
    lines.push(`- **Materials:** ${t.materials}`);
    lines.push(`- **Procedure:**`);
    t.procedure.forEach((step, si) => lines.push(`  ${si + 1}. ${step}`));
    if (t.differentiation) lines.push(`- **Differentiation:** ${t.differentiation}`);
    lines.push(`- **Teacher notes:** ${t.teacherNotes}`);
    lines.push("");
  });

  lines.push(`## Teacher implementation notes`);
  lines.push(list(report.implementationNotes));

  lines.push(`## Limitations and professional judgment`);
  lines.push(list(report.limitations));

  lines.push("---");
  lines.push("");
  lines.push(`_${REPORT_FRAMEWORK_NOTE}_`);
  lines.push("");

  return lines.join("\n");
}
